# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97237ff02a4012df3add8eff17f61b8185360d4551f5b6ee9292754c6fe027c52b955f7179f6d12c95131b2a43953b8c8b4210e39ead5f894d09b8af976a7a1e
  instagram_client_id: <%= ENV["INSTAGRAM_CLIENT_ID"] %>
  musicxmatch_api_key: <%= ENV["MUSICXMATCH_API_KEY"] %>
  wunderground_api_key: <%= ENV["WUNDERGROUND_API_KEY"] %>

test:
  secret_key_base: 98b696018c153c861e19dc2acd0364a1a46adae0447743399537a788e8cadd45d5f46617e211dacacbf78372f1ed8db1a9716ec62057b82bebb252d450eab464
  instagram_client_id: <%= ENV["INSTAGRAM_CLIENT_ID"] %>
  musicxmatch_api_key: <%= ENV["MUSICXMATCH_API_KEY"] %>
  wunderground_api_key: <%= ENV["WUNDERGROUND_API_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  instagram_client_id: <%= ENV["INSTAGRAM_CLIENT_ID"] %>
  musicxmatch_api_key: <%= ENV["MUSICXMATCH_API_KEY"] %>
  wunderground_api_key: <%= ENV["WUNDERGROUND_API_KEY"] %>
